### ISSUE TITLE
Chaine DSO - CA VAULT

### ISSUE THREAD

**Issue by ghost** [dnum-mi/dso-socle#1]
intégrer l'ajout du CA openshift

Tests en cours sur cluster 4-6.

- [ ]  Déployer sur environnnement MI (avec l'installation automatique complète de la chaine)

**Comment by ghost** [comment]
Dépendance à la tâche Gitlab.

**Comment by akramWewe** [comment]
@cedric-montagne  @this-is-tobi  Est ce qu'on est toujours bloqué sur ce ticket ?

**Comment by ghost** [comment]
Point débloqué.
