### ISSUE TITLE
Création d'un repo public sur Harbor pour y mettre les images transverses

### ISSUE THREAD

**Issue by plec** [dnum-mi/dso-socle#109]
Besoin d'un repo transverse pour les images transverse :) 
 - Bouchon Passage2
 - On a eu d'autres demandes de ce type que je n'ai plus en tête

**Comment by this-is-tobi** [comment]
Par défaut lors du déploiement Harbor, un projet public nommé `library` est créé automatiquement (il nécessite un compte pour push les images dedans mais pas pour les pull)
