### ISSUE TITLE
Compatibilité Kubernetes de la plateforme

### ISSUE THREAD

**Issue by this-is-tobi** [dnum-mi/dso-socle#89]
En tant qu'Ops je souhaite pouvoir déployer la plateforme sur une cluster Kubernetes.

## Tech

- [x] RBAC (gérer les clusterroles)
- [x] Fichiers `values.yaml` des charts Helm (gérer les configurations)
- [x] Opérateurs (ne pas utiliser d'opérateurs RedHat)
- [x] Ingress (gérer les routes / annotations spécifiques)
- [x] SCC / Network Policy
- [x] Ingress / Impact suppression de l'annotation Keycloack
- [x] Gestion du TLS interne
- [x] Namespace spécifique OCP ( Uniquement à renommer les NS potentiellement)

**Comment by Falltrades** [comment]
Hello,
J’ai commencé récemment à travailler sur le déploiement du socle sur un cluster Kubernetes « offline » (le cluster n’a pas accès à internet). 
La motivation principale réside à pouvoir provisionner des environnements de bac à sable.
Est-ce que l’équipe serait intéressée par une PR ?

**Comment by this-is-tobi** [comment]
Hello @Falltrades, effectivement si tu as des travaux en cours sur la compatibilité avec Kubernetes vanilla nous sommes intéressés pour échanger autour d'une PR (d'ailleurs si tu as des interrogations n'hésites pas à nous en faire part, nous ferons au mieux pour y répondre)

**Comment by Falltrades** [comment]
Hello @this-is-tobi, merci pour ton retour.
J'ai créé la PR https://github.com/cloud-pi-native/socle/pull/202 pour partager les travaux. L'idée est de ne pas impacter le déploiement par défaut qui est sur Openshift, et de faire passer des variables si on souhaite autre chose.

J'ai préféré faire une approche module par module plutôt que de considérer en globalité comme sur ton premier post (le temps de pouvoir déployer la totalité avant de revoir). Je tacle deux sujets indépendant en même temps (parce que je n'ai pas d'autres choix pour l'instant) : 
1) Déploiement sur un cluster Kubernetes.
2) Déploiement sur un cluster "offline" (cluster sans accès à internet).

C'est vrai que Cert-Manager perd un peu de sens quand le cluster est "offline", je ne suis pas sur de la pertinence à le déployer dans ce cas ?

J'ai fait mes tests avec :
- Infrastructure sur Openstack provisionné avec Terraform.
- Cluster Kubernetes déployé avec Kubespray.
- Gestion du storage avec cinder-csi-plugin.
- Choix de l'ingress : Traefik.

Actuellement je rencontre un soucis sur le Gitlab-Operator parce que l'image : gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1 est codé en dur sur https://gitlab.com/gitlab-org/cloud-native/gitlab-operator/-/blob/master/deploy/chart/templates/manager/deployment.yaml?ref_type=heads sans possibilité d'override par l'habituelle values.yaml. Je pourrai contourner en bricolant mais je suis preneur d'idée pour faire proprement.
